#!/bin/bash


# Generate synthetic data
python GenerateSyntheticData.py

# Process data
python ProcSyn1.py
python PostProcSyn1.py

python ProcSyn2.py
python PostProcSyn2.py

python ProcSyn3.py
python PostProcSyn3.py

python ProcSyn4.py
python PostProcSyn4.py